apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        echo "Cleaning up workspace..."
        rm -rf /workspace/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
spec:
  steps:
    - name: nose-tests
      image: python:3.9
      script: |
        pip install nose
        echo "Running unit tests with nose..."
        nosetests
